
export const CP_TOPICS = [
  "Arrays",
  "Strings",
  "Sorting",
  "Searching",
  "Greedy",
  "Dynamic Programming",
  "Graphs",
  "Trees",
  "Math",
  "Number Theory",
  "Bit Manipulation",
  "Two Pointers",
  "Stack",
  "Queue",
  "Heap",
  "Hashing",
  "Backtracking",
  "Geometry",
  "Segment Trees",
  "Disjoint Set Union",
  "Tries",
  "Game Theory",
  "Constructive Algorithms",
  "Interactive Problems",
];
